name: Validate Unit Files

on:
  push:
    branches:
      - main
    paths:
      - 'units/**'
      - 'schemas/**'
      - 'utils/validator.py'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  check_changes:
    name: Check for relevant changes
    runs-on: ubuntu-latest
    outputs:
      needs_validation: ${{ steps.check_files.outputs.needs_validation }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to properly check differences
      
      - name: Check for modified files
        id: check_files
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            # For push events, our path filter already handled this
            echo "needs_validation=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # For manual triggers, always validate
            echo "needs_validation=true" >> $GITHUB_OUTPUT
          else
            # For pull requests, check changed files
            git fetch origin ${{ github.base_ref }}
            
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)
            echo "Changed files:"
            echo "$CHANGED_FILES"
            
            if echo "$CHANGED_FILES" | grep -q -E '^units/|^schemas/|^utils/validator\.py'; then
              echo "Changes require validation"
              echo "needs_validation=true" >> $GITHUB_OUTPUT
            else
              echo "No changes requiring validation"
              echo "needs_validation=false" >> $GITHUB_OUTPUT
            fi
          fi
      
      - name: Validation status
        if: steps.check_files.outputs.needs_validation != 'true'
        run: |
          echo "## Validation Not Required" >> $GITHUB_STEP_SUMMARY
          echo "✅ No changes to units, schemas, or validator detected" >> $GITHUB_STEP_SUMMARY
          echo "Validation automatically passes" >> $GITHUB_STEP_SUMMARY

  validate:
    name: Validate Unit Schemas
    needs: check_changes
    if: needs.check_changes.outputs.needs_validation == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      
      - name: Validate unit files
        id: validate
        run: |
          python utils/validator.py --units

      - name: Generate index file
        if: success()
        run: |
          python utils/generate_index.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add units/index.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update units index.json [skip ci]"
            
      - name: Add validation summary
        if: always()
        run: |
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.validate.outcome }}" == "success" ]; then
            echo "✅ All unit files are valid" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some unit files have validation errors" >> $GITHUB_STEP_SUMMARY
            echo "Check the job logs for more details" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi 